config/routes.rb
Rails.application.routes.draw do
  get 'list/index'

  get 'member/index'

  get 'minicurso/index'

  get 'confirmation/index'

  get 'lista', to: "list#index", as: 'geral'

  resources :administrators
  get 'checkout/:id', to: 'checkout#create', as: 'checkout'

  get 'n/:id' => 'notifications#create'


  get 'registres/painel' => 'registres#painel'

  get 'member', to: 'member#index', as: 'index'

  resources :panelists
  resources :courses
  resources :contacts
  
  devise_for :users, :controllers  => {
             :registrations => 'users/registrations',
             :sessions => 'users/sessions'
             # ...
           }

  resources :minhainscricaos
  resources :palestra_inscricaos
  resources :palestras
  
  # root 'menu#index'
  root 'menu#new_index'
  get '/dashboard', to: 'menu#dashboard', as: 'dashboard'
  get '/certificado', to: 'menu#certificado', as: 'certificado'

  get 'pay/:id/user' => "checkout#create"


  get 'confirma/:id', to: "confirmation#index", as: 'confirmation'

  get 'menu/index'
  #get 'painel/admin'

  get 'inscricoes/index'
  
  get 'contato/index'

  get 'parceiros/index'

  get 'programacao/index'

  get 'inscricoes/index'

  get 'artigos/index'
  
  get 'comite_cientifico/index'

  get 'comissao_organizadora/index'

  get 'apresentacao/index'

  #get 'menu#index'
  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :telephone, presence: true
  validates :obs, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
	enum category: [:first_day, :second_day]

	validates :name, presence: true
	validates :description, presence: true

	has_many :registereds
	has_many :users,
		:through => :registereds

	def self.available dia
		cursos = Course.where( category: dia )
		confirmados = cursos.to_a.select {|c| c.registereds.where(pay: 1).count < 20 }
	end		
end

app/models/minhainscricao.rb
class Minhainscricao < ActiveRecord::Base
end

app/models/panelist.rb
class Panelist < ActiveRecord::Base
  enum status: [:confirmed, :unconfirmed]

  belongs_to :user

  validates :article, presence: true
end

app/models/registered.rb
class Registered < ActiveRecord::Base
	enum pay: [:unconfirmed, :confirmed]

	belongs_to :user
	belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  enum status: [:não_confirmado, :confirmado]
  
  #relactions
  has_many :registereds
  has_many :courses,
    :through => :registereds

  has_one :panelist

  validates :name, presence: true
  validates :cpf, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :telephone, presence: true
  validates :institution, presence: true
  validates :birthday, presence: true

  accepts_nested_attributes_for :registereds
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/programacao_controller.rb
class ProgramacaoController < ApplicationController
  def index
  end
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/minicurso_helper.rb
module MinicursoHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/panelists_helper.rb
module PanelistsHelper
end

app/helpers/parceiros_helper.rb
module ParceirosHelper
end

app/helpers/programacao_helper.rb
module ProgramacaoHelper
end

app/helpers/registres_helper.rb
module RegistresHelper
end

app/views/programacao/index.html.erb
<div class="row data-equalizer">

	<div class="large-10 large-centered columns">
		<%= image_tag 'Cronograma.png' %>	
	</div>

<br />
	

	 <div class="large-10 large-centered columns">
    		<div class="panel">
     			<div class="row">
        			
          
						<p>Palestra 1 - Internet das Coisas  - Harilton Araújo;</p>
						<p>Palestra 2 - Aplicação de apoio à decisão - Steve Mpinda; </p>
						<p>Palestra 3 - Processamento de Imagens - Rodrigo Veras; </p> 
						<p>Palestra 4 - Algoritmos Genéticos - Wener Sampaio; </p>
						


          			</div>
      			</div>
      			
      			<div class= "row">
                  
                    <h4><b>Minicursos G1 - 19/01</b></h4>
                      <div class="large-3 columns" > 
                    	 <a href = "https://www.arduino.cc"> <%= image_tag('arduino.jpg')%> </a>
                       <p class= "panel">
                       <a href = "http://lattes.cnpq.br/2994702103100444"> <b>Thiago José Lima</b></a> E
                       <a href = "http://lattes.cnpq.br/3543623658372872"> <b>Allan Jheyson Ramos</b></a>
                       </p>
                       </div>
                        <div class="large-3 columns" > 
                     <a href = "https://www.facebook.com/GestorBox"> <%= image_tag('gestorbox.jpg')%></a>
                     <a href = "http://lattes.cnpq.br/7997723359146798"><p class="panel">Aislan Rafael</p></a>
                   </div>
                    <div class="large-3 columns" > 
                    <a href = "http://www.coreldraw.com"><%= image_tag('CorelDRAW-Graphics-Suite-X7.jpg')%></a>
                     <a href = "https://www.facebook.com/Marcelo.MSDamasceno"><p class="panel">Marcelo Damasceno</p></a>
                                       </div>
                   <div class="large-3 columns" > 
                    <a href = "https://en.wikipedia.org/wiki/Real-time_web"><%= image_tag('RealTimeWeb.jpg')%></a>
                    <a href = " http://lattes.cnpq.br/2010264560196042"> <p class="panel">Guilherme Feitosa</p></a>
                  </div>

        		</div>





            <div class="row">
            <h4><b>Minicursos G2 - 20/01</b></h4>
               <div class="large-3 columns" > 
                <a href = "https://www.android.com/"><%= image_tag('android-logo.jpg')%></a>
                <a href = "https://www.facebook.com/laurentino.moura?fref=ts"><p class="panel">Laurentino Moura</p></a>
              </div>

               <div class="large-3 columns" > 
              <a href = "https://www.python.org"><%=image_tag('python.jpg')%></a>
              <p class="panel">Jonnison Lima</p>
              </div>
               <div class="large-3 columns" > 
                <a href = "https://pt.wikipedia.org/wiki/LaTeX"><%=image_tag('Latex.jpg')%></a>
                <a href = "http://lattes.cnpq.br/3734588405818556"><p class="panel">Romuere Silva</p></a>
              </div>
               <div class="large-3 columns" > 
                <a href = ""><%= image_tag('2.jpg') %></a>
                <p class="panel">Marcelino Mendes E Aislan Maia</p>
              </div>

              </div>
         
    		</div>
           </div>
	
	<p>
				Dúvidas ou esclarecimentos entre em <%= link_to 'Contato',new_contact_path %> 
				</p>
</div>