config/routes.rb
Rails.application.routes.draw do
  get 'list/index'

  get 'member/index'

  get 'minicurso/index'

  get 'confirmation/index'

  get 'lista', to: "list#index", as: 'geral'

  resources :administrators
  get 'checkout/:id', to: 'checkout#create', as: 'checkout'

  get 'n/:id' => 'notifications#create'


  get 'registres/painel' => 'registres#painel'

  get 'member', to: 'member#index', as: 'index'

  resources :panelists
  resources :courses
  resources :contacts
  
  devise_for :users, :controllers  => {
             :registrations => 'users/registrations',
             :sessions => 'users/sessions'
             # ...
           }

  resources :minhainscricaos
  resources :palestra_inscricaos
  resources :palestras
  
  # root 'menu#index'
  root 'menu#new_index'
  get '/dashboard', to: 'menu#dashboard', as: 'dashboard'
  get '/certificado', to: 'menu#certificado', as: 'certificado'

  get 'pay/:id/user' => "checkout#create"


  get 'confirma/:id', to: "confirmation#index", as: 'confirmation'

  get 'menu/index'
  #get 'painel/admin'

  get 'inscricoes/index'
  
  get 'contato/index'

  get 'parceiros/index'

  get 'programacao/index'

  get 'inscricoes/index'

  get 'artigos/index'
  
  get 'comite_cientifico/index'

  get 'comissao_organizadora/index'

  get 'apresentacao/index'

  #get 'menu#index'
  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :telephone, presence: true
  validates :obs, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
	enum category: [:first_day, :second_day]

	validates :name, presence: true
	validates :description, presence: true

	has_many :registereds
	has_many :users,
		:through => :registereds

	def self.available dia
		cursos = Course.where( category: dia )
		confirmados = cursos.to_a.select {|c| c.registereds.where(pay: 1).count < 20 }
	end		
end

app/models/minhainscricao.rb
class Minhainscricao < ActiveRecord::Base
end

app/models/panelist.rb
class Panelist < ActiveRecord::Base
  enum status: [:confirmed, :unconfirmed]

  belongs_to :user

  validates :article, presence: true
end

app/models/registered.rb
class Registered < ActiveRecord::Base
	enum pay: [:unconfirmed, :confirmed]

	belongs_to :user
	belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  enum status: [:não_confirmado, :confirmado]
  
  #relactions
  has_many :registereds
  has_many :courses,
    :through => :registereds

  has_one :panelist

  validates :name, presence: true
  validates :cpf, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :telephone, presence: true
  validates :institution, presence: true
  validates :birthday, presence: true

  accepts_nested_attributes_for :registereds
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /administrators
  # GET /administrators.json
  def index
    @users = User.all
    @shirts = User.where(status: 1)
    @artigos = Panelist.all
    @courses = Course.all
    @contacts = Contact.all
    authorize @users
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to @administrator, notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to @administrator, notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params[:administrator]
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/minicurso_helper.rb
module MinicursoHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/panelists_helper.rb
module PanelistsHelper
end

app/helpers/parceiros_helper.rb
module ParceirosHelper
end

app/helpers/registres_helper.rb
module RegistresHelper
end

app/views/administrators/_form.html.erb
<%= form_for(@administrator) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', @administrator %> |
<%= link_to 'Back', administrators_path %>

app/views/administrators/index.html.erb
<div class="row">

  <div class="large-12 columns">
    <h1><%= link_to 'Lista Geral',member_index_path %></h1>
    <h1><%= link_to 'Lista Geral não confirmados',list_index_path %></h1>
    <h1>Painel Administrador</h1>
                      <div class="large-6 columns">
                        <h3>Artigos</h3>  
                          <table>
                                <thead>
                                  <tr>
                                    <th>Pessoa</th>
                                    <th>Camisa</th>
                                    
                                  </tr> 
                                </thead>
                                <tbody>
                                  <% @shirts.each do |user| %>
                                    <% if user.shirt != ''%>
                                    <tr>
                                      <td><%= user.name %></td>
                                      <td><%= user.shirt %></td>  
                                    </tr>
                                    <% end %>
                                  <% end %>
                                </tbody>    
                            </table>
                    
                      </div>


                        <div class="large-6 columns">
                          <h3>Cursos</h3>

                            <table>
                                <thead>
                                  <tr>
                                      <th>Nome</th>
                                    <th>Categoria</th>
                                       <th>Confirmados</th>
                                       <th>Não Confirmados</th>
                                      <th colspan="2"></th>
                                  </tr>
                                </thead>

                                <tbody>
                                  <% @courses.each do |course| %>
                                    <tr>
                                      <td><%= course.name %></td>
                                     <td><%= course.category %></td>
                                     <td><%= course.registereds.where(pay: 1).count %></td>
                                     <td><%= course.registereds.where(pay: 0).count %></td>
                                      <td><%= link_to 'Exibir', course %></td>
                                      <td><%= link_to 'Apagar', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                    </tr>
                                  <% end %>
                                </tbody>
                                <%= link_to 'Novo Curso', new_course_path %>
                            </table>
                        </div>
  </div>

      <div class="large-12 columns">

                        <div class="large-6 columns">
                        <h3>Contatos</h3>

                          <table>
                              <thead>
                                <tr>
                                    <th>Nome</th>
                                  <th>Mensagem</th>
                                    <th colspan="2"></th>
                                </tr>
                              </thead>

                              <tbody>
                                     <% @contacts.each do |contact| %>
                                <tr>
                                    <td><%= contact.name %></td>
                                    <td><%= contact.obs %></td>
                                    <td><%= link_to 'Show', contact %></td>
                                    <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                </tr>
                                <% end %>
                              </tbody>
                          </table>

                        

                      </div>


                      <div class="large-6 columns">
                        <h3>Inscritos</h3>
                        
                          <table>
                              <thead>
                                <tr>
                                    <th>Nome</th>
                                    <th>e-mail</th>
                                    <th>Pagamento</th>
                                    <th>id</th>
                                    <th colspan="2"></th>
                                </tr>
                              </thead>

                              <tbody>
                                <% @users.each do |user| %>
                                  <tr>
                                    <td><%= user.name %></td>
                                    <td><%= user.email %></td>
                                    <td><%= user.status %></td>
                                    <td><%= user.id %></td>
                                    <td><%= link_to 'confirmar', confirmation_path(user.id) %></td>
                                    
                                  </tr>
                                <% end %>
                              </tbody>
                          </table>
                      </div>
    
      </div>
</div>

app/views/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', administrators_path %>

app/views/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_administrator_path(@administrator) %> |
<%= link_to 'Back', administrators_path %>