config/routes.rb
Rails.application.routes.draw do
  get 'list/index'

  get 'member/index'

  get 'minicurso/index'

  get 'confirmation/index'

  get 'lista', to: "list#index", as: 'geral'

  resources :administrators
  get 'checkout/:id', to: 'checkout#create', as: 'checkout'

  get 'n/:id' => 'notifications#create'


  get 'registres/painel' => 'registres#painel'

  get 'member', to: 'member#index', as: 'index'

  resources :panelists
  resources :courses
  resources :contacts
  
  devise_for :users, :controllers  => {
             :registrations => 'users/registrations',
             :sessions => 'users/sessions'
             # ...
           }

  resources :minhainscricaos
  resources :palestra_inscricaos
  resources :palestras
  
  # root 'menu#index'
  root 'menu#new_index'
  get '/dashboard', to: 'menu#dashboard', as: 'dashboard'
  get '/certificado', to: 'menu#certificado', as: 'certificado'

  get 'pay/:id/user' => "checkout#create"


  get 'confirma/:id', to: "confirmation#index", as: 'confirmation'

  get 'menu/index'
  #get 'painel/admin'

  get 'inscricoes/index'
  
  get 'contato/index'

  get 'parceiros/index'

  get 'programacao/index'

  get 'inscricoes/index'

  get 'artigos/index'
  
  get 'comite_cientifico/index'

  get 'comissao_organizadora/index'

  get 'apresentacao/index'

  #get 'menu#index'
  match ':controller(/:action(/:id))', :via => [:get, :post]
end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :name, presence: true
  validates :email, presence: true,format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :telephone, presence: true
  validates :obs, presence: true
end

app/models/course.rb
class Course < ActiveRecord::Base
	enum category: [:first_day, :second_day]

	validates :name, presence: true
	validates :description, presence: true

	has_many :registereds
	has_many :users,
		:through => :registereds

	def self.available dia
		cursos = Course.where( category: dia )
		confirmados = cursos.to_a.select {|c| c.registereds.where(pay: 1).count < 20 }
	end		
end

app/models/minhainscricao.rb
class Minhainscricao < ActiveRecord::Base
end

app/models/panelist.rb
class Panelist < ActiveRecord::Base
  enum status: [:confirmed, :unconfirmed]

  belongs_to :user

  validates :article, presence: true
end

app/models/registered.rb
class Registered < ActiveRecord::Base
	enum pay: [:unconfirmed, :confirmed]

	belongs_to :user
	belongs_to :course
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:normal_user, :admin]
  enum status: [:não_confirmado, :confirmado]
  
  #relactions
  has_many :registereds
  has_many :courses,
    :through => :registereds

  has_one :panelist

  validates :name, presence: true
  validates :cpf, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :telephone, presence: true
  validates :institution, presence: true
  validates :birthday, presence: true

  accepts_nested_attributes_for :registereds
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/panelists_controller.rb
class PanelistsController < ApplicationController
  before_action :set_panelist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:new,:create]

  # GET /panelists
  # GET /panelists.json
  def index
    @panelists = Panelist.all
    authorize @panelists
  end

  # GET /panelists/1
  # GET /panelists/1.json
  def show
    authorize @panelist
  end

  # GET /panelists/new
  def new
    @panelist = Panelist.new
  end

  # GET /panelists/1/edit
  def edit
  end

  # POST /panelists
  # POST /panelists.json
  def create
    @panelist = Panelist.new(panelist_params)

    respond_to do |format|
      if @panelist.save
        format.html { redirect_to @panelist, notice: 'Panelist was successfully created.' }
        format.json { render :show, status: :created, location: @panelist }
      else
        format.html { render :new }
        format.json { render json: @panelist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /panelists/1
  # PATCH/PUT /panelists/1.json
  def update
    respond_to do |format|
      if @panelist.update(panelist_params)
        format.html { redirect_to @panelist, notice: 'Panelist was successfully updated.' }
        format.json { render :show, status: :ok, location: @panelist }
      else
        format.html { render :edit }
        format.json { render json: @panelist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /panelists/1
  # DELETE /panelists/1.json
  def destroy
    authorize @panelist
    @panelist.destroy
    respond_to do |format|
      format.html { redirect_to panelists_url, notice: 'Panelist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panelist
      @panelist = Panelist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panelist_params
      params.require(:panelist).permit(:article, :user_id)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artigos_helper.rb
module ArtigosHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/contato_helper.rb
module ContatoHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/helpers/member_helper.rb
module MemberHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/minicurso_helper.rb
module MinicursoHelper
end

app/helpers/painel_helper.rb
module PainelHelper
end

app/helpers/panelists_helper.rb
module PanelistsHelper
end

app/helpers/parceiros_helper.rb
module ParceirosHelper
end

app/helpers/programacao_helper.rb
module ProgramacaoHelper
end

app/helpers/registres_helper.rb
module RegistresHelper
end

app/views/panelists/_form.html.erb
<%= form_for(@panelist) do |f| %>
  <% if @panelist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@panelist.errors.count, "error") %> prohibited this panelist from being saved:</h2>

      <ul>
      <% @panelist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :article %><br>
    <%= f.text_field :article %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/panelists/edit.html.erb
<h1>Editing Panelist</h1>

<%= render 'form' %>

<%= link_to 'Show', @panelist %> |
<%= link_to 'Back', panelists_path %>

app/views/panelists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de expositores</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @panelists.each do |panelist| %>
      <tr>
        <td><%= panelist.article %></td>
        <td><%= panelist.user %></td>
        <td><%= link_to 'Mostrar', panelist %></td>
        <td><%= link_to 'Editar', edit_panelist_path(panelist) %></td>
        <td><%= link_to 'Apagar', panelist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo', new_panelist_path %>

app/views/panelists/new.html.erb
<h1>New Panelist</h1>

<%= render 'form' %>

<%= link_to 'Voltar', panelists_path %>

app/views/panelists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @panelist.article %>
</p>

<p>
  <strong>User:</strong>
  <%= @panelist.user.name %>
</p>

<%= link_to 'Editar', edit_panelist_path(@panelist) %> |
<%= link_to 'Voltar', administrators_path %>